FROM golang:latest

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        inotify-tools \
 && rm -rf /var/lib/apt/lists/*

RUN /app/install_dependencies.sh