FROM golang:latest

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        inotify-tools \
 && rm -rf /var/lib/apt/lists/*

RUN go get -v github.com/jinzhu/gorm \
 && go get -v github.com/lib/pq \
 && go get -v github.com/robfig/cron \
 && go get -v gopkg.in/resty.v1 \
 && go get -v github.com/spf13/viper