DO $$
BEGIN
  BEGIN
    ALTER TABLE game ALTER COLUMN app_id TYPE BIGINT USING app_id::BIGINT;
    EXCEPTION
    WHEN UNDEFINED_TABLE THEN RAISE NOTICE '';
  END;
END $$;

DO $$
BEGIN
  BEGIN
    ALTER TABLE game_snapshot ALTER COLUMN game_id TYPE BIGINT USING game_id::BIGINT;
    EXCEPTION
    WHEN UNDEFINED_TABLE THEN RAISE NOTICE '';
  END;
END $$;